branches:
  only:
  - travis-test
  
language: c

env:
 - NODE=COORDINATOR BAUD=115200 JENNIC_CHIP=JN5168 JENNIC_CHIP_FAMILY=JN516x

jobs:
  include:
    - stage: test
      os: windows
      before_script:
        - choco install -y make
        - 7z x /c/Users/travis/build/ISO-B/ZiGate-firmware/Module_Radio/Firmware/src/sdk/Tools.7z -o/c/Users/travis/build/ISO-B/ZiGate-firmware/Module_Radio/Firmware/src/sdk/ -y
      script: make -C /c/Users/travis/build/ISO-B/ZiGate-firmware/Module_Radio/Firmware/src/ZiGate/Build/ZigbeeNodeControlBridge/ all