branches:
  only:
  - travis-test
  
language: c

env:
 - NODE=COORDINATOR BAUD=115200 JENNIC_CHIP=JN5168 JENNIC_CHIP_FAMILY=JN516x

jobs:
  include:
    - stage: test
      os: windows
      before_script:
        - choco install -y msys2
        - ls
        - ls C:\
        - ls C:\tools\msys64\bin\
      script: make --help
      #script: cmake -C Module_Radio/Firmware/src/ZiGate/Build/ZigbeeNodeControlBridge/ all